### PR TITLE
WIP: reference revisions by hash when tagging a release

### PR DESCRIPTION
**Pull request by valldrac**

### CODE REVIEW

**Comment by valldrac** [comment]
I've tested the python script and It seems to work well. However, I modified `manage.sh` without actually running it.

Maybe makes more sense to not change `manage.sh` for now. Instead, run `update_revision_hashes.py` manually after tagging a release, and then force push the tagged manifest to the repo platform_manifest, after verying the script has updated the hashes on it correctly?

**Comment by chirayudesai** [comment]
Another somewhat relevant thing can be the `repo manifest` command.

It's for a synced repo rather than the setup here but achieves the same thing. It also has an `upstream` entry which has the branch/tag in addition to `revision`.

`<project name="device/generic/common" revision="06c6585077b70bfea8781b770a88398c185ef2d2" upstream="refs/tags/android-10.0.0_r33" groups="pdk"/>`

**Comment by valldrac** [comment]
Thanks @chirayudesai. I didn't know that command. I guess it'd be better to use it instead of my custom script. But as you said, the repo needs to be synced after tagging the projects and updating the manifest with the new release tag.
Another different is the `repo manifest` get the hash from HEAD, but my tool get the hash of the annotated tag, which is probably bad?

**Comment by thestinger** [comment]
I'd rather do this without `repo` so that I won't need to do anything manually and we'll be able to move away from sha1 as soon as git supports it instead of when repo supports it after git.

**Comment by thestinger** [comment]
It might be best to use `repo` for now though.

**Comment by thestinger** [comment]
One advantage is being able to verify the signatures in the usual way before generating the hash-based manifest.

**Comment by valldrac** [comment]
Makes sense. At least now we have the skeleton to modify XML in an easy way preserving the formatting, if we need that it in the future.

Feel free to close this PR.

**Comment by thestinger** [comment]
`repo manifest -r` does work but the workflow is pretty annoying. I need to think about the best way to deal with this.

**Pull request closed without merging**
